### ISSUE TITLE
URL编码无法编码字母

### ISSUE THREAD

**Issue by Fridgffy** [ffffffff0x/BerylEnigma#10]
![image](https://user-images.githubusercontent.com/52872824/163567544-29aba04c-a78e-4f51-8280-0d7dae43eb8e.png)

**Comment by RyuZUSUNC** [comment]
![image](https://user-images.githubusercontent.com/16266917/163702118-e6685658-e025-4613-a5e2-a1dbe0ae1a97.png)

已添加编码所有字符功能 @Fridgffy
