### ISSUE TITLE
unicode编码无法编码字母

### ISSUE THREAD

**Issue by Fridgffy** [ffffffff0x/BerylEnigma#12]
![image](https://user-images.githubusercontent.com/52872824/179916079-4ee0f2ea-1b2c-4eed-b6d6-8f5bdde9ab44.png)

**Comment by RyuZUSUNC** [comment]
![image](https://user-images.githubusercontent.com/16266917/179980368-a7090697-bbb0-4d22-8774-1a08d4dbde08.png)
已更新
