### ISSUE TITLE
mac os  12.5 无法启动程序

### ISSUE THREAD

**Issue by cqrlhz** [ffffffff0x/BerylEnigma#14]
mac os  12.5 无法启动程序
<img width="229" alt="image" src="https://user-images.githubusercontent.com/63200706/182060843-92c9dc40-a335-4f02-9f30-aff0e3b82f76.png">

**Comment by RyuZUSUNC** [comment]
请提供更多的报错信息与系统信息用以排查问题。 @cqrlhz

**Comment by cqrlhz** [comment]
2.6 GHz 六核Intel Core i7   系统默认java 1.8

**Comment by cqrlhz** [comment]
安装了 java 11    17  但系统默认为1.8 @RyuZUSUNC

**Comment by cqrlhz** [comment]
并且app包 也移动到 程序文件夹

**Comment by RyuZUSUNC** [comment]
程序不需要安装java环境，请提供更多程序运行时异常的信息。

**Comment by cqrlhz** [comment]
mac 日志

<img width="793" alt="image" src="https://user-images.githubusercontent.com/63200706/182074852-85b180ed-64b4-4d50-9676-651e6b62104e.png">


```
assessment granted for BE-BerylEnigma-mac-x86.zip by _XProtect
com.apple.message.domain: com.apple.security.assessment.outcome2
com.apple.message.signature2: bundle:UNBUNDLED
com.apple.message.signature3: BE-BerylEnigma-mac-x86.zip
com.apple.message.signature: granted:_XProtect
com.apple.message.signature5: UNKNOWN
com.apple.message.signature4: 3
SenderMachUUID: 87D4E8E2-2AD8-3686-B47B-C931B5B083BC

```

**Comment by cqrlhz** [comment]
使用mac 自带解压软件  解压出查询 报“程序无法打开”  使用第三方解压软件 mac日志 不会报解压相关错误 打 打开软件报“程序损坏”

**Comment by cqrlhz** [comment]
已解决  ，mac 下解压 会导致程序损坏,无法正常运行 ，可在Windows下解后 复制到mac  可正常运行

**Comment by cqrlhz** [comment]
请问 大表哥 如何 更改 工具 颜色 本人不喜欢 白色   想要黑色

**Comment by RyuZUSUNC** [comment]
@cqrlhz 是的。我的MAC朋友把app传给，我用win打包的，刚刚传了一个mac打包的软件包在Releases里，你可以下载试试。

关于黑色版本的话，目前没有，正在开发中，我看看能不能在这周写完。

**Comment by cqrlhz** [comment]
Releases里的程序包 在 mac下解压 依然报“程序损坏”

**Comment by RyuZUSUNC** [comment]
@cqrlhz 已经完成黑暗模式的制作
本地测试1.12.5的mac-x86版本下载解压后可以使用
