### ISSUE TITLE
mac 无法打开 Intel(big sur)

### ISSUE THREAD

**Issue by hello-sucess** [ffffffff0x/BerylEnigma#15]
<img width="253" alt="image" src="https://user-images.githubusercontent.com/31380144/184580939-fc15943e-c19a-466c-9df6-a20e96c93142.png">

**Comment by RyuZUSUNC** [comment]
软件在 macOS montersy(intel) 上运行正常，很抱歉没有能力为旧版本提供兼容。
如果可以的话请尝试安装 JDK17 与 Maven 后使用 jpackage 文件夹内的 macPack 脚本自行编译。 @hello-sucess

**Comment by hello-sucess** [comment]
感谢、我已经在升级系统了。。。
