### ISSUE TITLE
建议：文档增加项目名字的由来和发音

### ISSUE THREAD

**Issue by ttimasdf** [ffffffff0x/BerylEnigma#5]
每次我想打开本项目的github的时候，我只能从本地Everything搜索`enigma`，因为jar包命名带有项目完整的名字。我输错过的名字有：

- berlyenigma
- beryenigma
- berlenigma
- berylenigma
- bearyenigma

从我的角度来看，非常影响开源项目的推广。在搜索引擎靠用途已经很难检索到了，从名字再搜不到……真的就会被忘记了。

**Comment by RyuZUSUNC** [comment]
谢谢您提出的建议，近期会在文档中添加相关信息。对于名字不方便搜索的问题，之后会尝试将项目与可执行文件名称改为简称 BE 或 be-BerylEnigma这样的格式，看看是否能有所改善。
