### ISSUE TITLE
相互学习

### ISSUE THREAD

**Issue by Leon406** [ffffffff0x/BerylEnigma#6]
现代密码学可以参考下,基于kotlin + tornadoFx
https://github.com/Leon406/ToolsFx/tree/dev

**Comment by Asura88** [comment]
这个我试了，评价是不好用，okk编码都报错

**Comment by Leon406** [comment]
> 这个我试了，评价是不好用，okk编码都报错
j建议多学学英语, 英语翻一下就知道了

**Comment by Asura88** [comment]
直接放弃了，谢谢



---原始邮件---
发件人: "Leon ***@***.***&gt;
发送时间: 2022年11月16日(周三) 晚上8:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ffffffff0x/BerylEnigma] 相互学习 (#6)




  
这个我试了，评价是不好用，okk编码都报错
 j建议多学学英语, 英语翻一下就知道了
