### ISSUE TITLE
[issue] 栅栏密码的加密有些问题

### ISSUE THREAD

**Issue by No-Github** [ffffffff0x/BerylEnigma#8]
栅栏密码的加密有些问题

kanbbrgghjl{zb____}vtlaln

密钥为 7 时加密结果为 kg_lah_anj_lbl_nb{}rzvgbt
![image](https://user-images.githubusercontent.com/18167071/135960656-040ad312-6b47-4c5d-9c97-f09a9a84bf81.png)

实际结果应该为 kzna{blnl_abj_lbh_trg_vg}

可以用这个验证下结果 http://www.hiencode.com/railfence.html
![image](https://user-images.githubusercontent.com/18167071/135960651-475d3057-25ed-48e7-b618-1c9d2c7ad329.png)

**Comment by RyuZUSUNC** [comment]
https://www.qqxiuzi.cn/bianma/zhalanmima.php

![image](https://user-images.githubusercontent.com/16266917/135972094-d4b048da-85d7-4ec0-a91f-b608d49a0868.png)


http://www.metools.info/code/fence154.html

![image](https://user-images.githubusercontent.com/16266917/135972127-c1e83d7f-a539-4de3-82d2-bd5ae1afe3a8.png)


栅栏密码有多种不同的实现，这个工具实现的是标准型栅栏加密，而当前flag使用的是W型栅栏加密，可以参照上述两个网站

在之后的更新中会加入此项功能
